# MAE6225 Travis CI.

os: linux
language: python
python:
- "3.6"
sudo: false

before_install:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- echo ". $HOME/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
- source $HOME/.bashrc
- conda activate
- conda env create --quiet --file environment.yaml
- conda activate py36-mae6225

install:
- python setup.py develop

script:
- python tests/all.py

notifications:
  email: false

branches:
  only:
  - master
  - develop
